### PR TITLE
Update the location of the jrpc2 module.

### PR DESCRIPTION
**Pull request by creachadair**
The bitbucket.org/creachadair/jrpc2 module has been rehomed to github.com. This change updates the import paths and the go.mod and go.sum files, and the pointer in the README.  It does not otherwise change the existing use.

Sorry I missed this usage when I was doing the initial migration. It appears godoc.org only updates dependencies when someone visits the documentation for the dependent. In retrospect that makes sense, but I probably should have done a search first.

### CODE REVIEW

**Comment by juliosueirasED** [comment]
Thanks for giving the heads up and creating this pr

**Comment by juliosueiras** [comment]
Thanks for giving the heads up and creating this pr

**Comment by creachadair** [comment]
Unfortunately, Travis seems not to have liked the change because I didn't manage to update the Nix digest for the package. Is there some easy way to do that? (I'll be happy to send another PR)

**Comment by juliosueiras** [comment]
=) is fine , already did a commit to changed the hash in default.nix

**Comment by creachadair** [comment]
Ah, thanks.

**Pull request merged**
